[connections.snowflake]
account = "TCNMJLT.PZ12020"
user = "ANTOR7S"
password = "pwdAMT123477$"
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "SNOWPROJ"
schema = "PUBLIC"
client_session_keep_alive = true
